### ISSUE TITLE
module 'urllib3.exceptions' has no attribute 'SubjectAltNameWarning'

### ISSUE THREAD

**Issue by galaad** [stormshield/python-SNS-API#10]
### Description
I am encountering an issue while using the stormshield.sns.sslclient library.
When running my code, I receive the following error message:

```
AttributeError: module 'urllib3.exceptions' has no attribute 'SubjectAltNameWarning'
```

### Steps to reproduce

- Install the stormshield.sns.sslclient library.
- Import the library and execute the code that triggers the error.
- Observe the AttributeError with the mentioned module and attribute.

### Environment

- Python version: 3.10.0
- Operating system: Ubuntu 22.01
- Dependencies: 
  - stormshield.sns.sslclient 1.0.6
  - urllib3  2.0.2

### Code exemple

```
from stormshield.sns.sslclient import SSLClient

firewall = SSLClient(
            host=self.hostname,
            user=self.username,
            port=self.port,
            password=self.password,
            sslverifyhost=False,
            sslverifypeer=False,
        )
```

### Additional information

I have verified my environment and dependencies, and I'm confident that they meet the requirements specified by the stormshield.sns.sslclient library. I have also searched for similar issues but couldn't find a solution. I believe this issue is specific to the library itself.

Any assistance in resolving this issue would be greatly appreciated. Thank you.

**Comment by Yamakaky** [comment]
I believe this is linked to https://github.com/psf/requests/releases/tag/v2.30.0. This library should add either a `requests<2.30` or `urllib3<2` dependency constraint.

**Comment by remip2** [comment]
Fix pushed on master, please give it a try. I'll publish the update on pypi in a few days after some more tests.

**Comment by remip2** [comment]
I reopen this issue, something is wrong with certificate authentication and urllib3 2.0.0

**Comment by remip2** [comment]
1.1.0 has been published
