### ISSUE TITLE
Parenthesis in object name

### ISSUE THREAD

**Issue by mjuston-uqt** [stormshield/python-SNS-API#14]
Hello,

We're facing an issue with the library when some objects (groups in our particular case) has parenthesis in their names.

For instance, we have this situation:

> config object list type=group
> [Object]
> type=group global=1 name=group(test) nb_elements=2 modify=1 comment=test
> 

When the same command is sent through the library, we get `group` as object name. The portion "(test)" is removed by the parser.

My understanding is it comes from the "allowed" characters list that is passed to `shlex`. We would need to add "()" in  `lexer.wordchars`

cf https://github.com/stormshield/python-SNS-API/blob/f2e7c08f1109de91ebbc927bc072ec4480cf5625/stormshield/sns/configparser.py#L97

Could that line be modified ?

Regards,
Miguel

**Comment by remip2** [comment]
You can test on master

**Comment by mjuston-uqt** [comment]
Thanks
