### ISSUE TITLE
Allow timeout configuration in send_command

### ISSUE THREAD

**Issue by Yamakaky** [stormshield/python-SNS-API#9]
Most commands are short, so I configured a 20s timeout. However, the configuration restore for example can take longer than that. My fix is to temporarily increase the timeout:
```python
old_timeout = client.conn_options["timeout"]
client.conn_options["timeout"] = 60
try:
    resp = client.send_command(f"CONFIG RESTORE refresh=1 list=all < {source_path}")
finally:
    client.conn_options["timeout"] = old_timeout
```
It would be cleaner to be able to pass a timeout (and maybe other parameters?) to `send_command`.

**Comment by remip2** [comment]
You can know use:

`client.send_command("CONFIG BACKUP list=all > /tmp/backup.na", timeout=None)`

Regards,

**Comment by Yamakaky** [comment]
Nice! Any timeline for the next release?

**Comment by remip2** [comment]
It has just been published on pypi
